"""
config_handler 类型存根。
统一从 config 目录下的 JSON 文件加载配置；默认路径与当前 config 布局一致：

  config/
  ├── driver/driver.json       # 浏览器驱动（Chrome_Path, Chrome_Driver_Path）
  ├── model/rag.json           # RAG 模型（chat_model_name, embedding_model_name）
  ├── vector_store/chroma.json # Chroma 向量库（collection_name, k, info_path 等）
  ├── prompts/prompts.json     # 提示词路径（main_prompt_path, rag_summarize_prompt_path 等）
  ├── websites/
  │   ├── bbs.json             # BBS 论坛 URL（BBS_Url）
  │   └── official_websites.json
  └── data/
      └── raw/webdata_raw.json # 爬取数据配置（data_path, data_type）
"""
from pathlib import Path

def _load_json(config_path: str, encoding: str = "utf-8") -> dict: ...
def load_bbs_config(config_path: str | None = None, encoding: str = "utf-8") -> dict: ...
def load_driver_config(config_path: str | None = None, encoding: str = "utf-8") -> dict: ...
def load_prompts_config(config_path: str | None = None, encoding: str = "utf-8") -> dict: ...

def load_websites_config(config_path: str | None = None, encoding: str = "utf-8") -> dict: ...
def get_rag_config_path(path: str = "config/model/rag.json") -> Path: ...
def load_rag_config(path: str = "config/model/rag.json", encoding: str = "utf-8") -> dict: ...
def get_chroma_config_path(path: str = "config/vector_store/chroma.json") -> Path: ...
def load_chroma_config(path: str = "config/vector_store/chroma.json", encoding: str = "utf-8") -> dict: ...
def get_bbs_url() -> str: ...
def load_webdata_raw_config(config_path: str | None = None, encoding: str = "utf-8") -> dict: ...
def load_login_config(config_path: str | None = None, encoding: str = "utf-8") -> dict: ...

driver_conf: dict
bbs_conf: dict
prompts_conf: dict
rag_conf: dict
chroma_conf: dict
